### ISSUE TITLE
[suggestion] Add e.proportionX and Y relative to element Width and Height

### ISSUE THREAD

**Issue by dariuszsikorski** [benmajor/jQuery-Touch-Events#101]
Here is the prototype: https://jsfiddle.net/ezzkz7L6/1/

Add new property for events **tapend** and **tapmove** - a proportion factor , which is:

```
e.proportionX = distanceX / targetElementWidth
e.proportionY = distanceY / targetElementHeight
```

This would allow to manipulate the other elements with transform proportionally to swipe distance.
For example: when you drag finger to the left - a little indicator of navigation will gradually appear.

Other usage: writing custom swipe rules:
If user swiped `0.33` (33%) of `targetElementWidth` in 1second, then hide it.

**Comment by benmajor** [comment]
Thanks. I will add this as a new feature for v2.

**Comment by dariuszsikorski** [comment]
That would be great!

**Comment by benmajor** [comment]
I am working on v2 now, but am dropping this from the feature list unfortunately. It's beyond the scope of the lib, since it will tightly couple the events together too much. It would be easy for the client to implement this using callback data, so I won't be adding this.
