### ISSUE TITLE
Android 4 listener not being attached

### ISSUE THREAD

**Issue by thegalah** [benmajor/jQuery-Touch-Events#103]
Works perfectly on every device except on android 4. None of the listeners in the library attach

**Comment by benmajor** [comment]
Thanks; is this inside the Android Browser, or Google Chrome?

**Comment by thegalah** [comment]
It's a webview within a cordova app which I think uses the default android browser if i'm not mistaken

**Comment by benmajor** [comment]
Yes, it will be the native browser. Thanks for the heads-up; I'll try to locate a native Android 4 device to test. Do you have the specific version?

**Comment by thegalah** [comment]
No problem :) great work on the library by the way!
It seems to be on any version of Android 4, but definitely know it happens on version 4.4

**Comment by benmajor** [comment]
OK, thanks :) Will look into this and update the Issue when it's fixed. I *think* it's just related to the event bindings, but strange that nothing works. Is there any way you can see if there are any logs in the console at all?

**Comment by thegalah** [comment]
I don't see anything in the console, no warnings or errors

**Comment by benmajor** [comment]
I just tested the demo link (http://lincweb.co.uk/labs/jquery-touch-events/demo/) on Android 4.4 via BrowserStack, and the event trace is correctly displaying the events, so I *think* the lib is working correctly (at least in the demo). 

https://www.browserstack.com/start#os=android&os_version=4.4&device=Samsung+Galaxy+Note+4&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Flincweb.co.uk%2Flabs%2Fjquery-touch-events%2Fdemo%2F&speed=1

Can you confirm for me if the demo works in the default Android browser on your device?

**Comment by thegalah** [comment]
I tested in the simulator and it seems to work. I do not have an android 4 device to test with however (I've just been getting multiple reports (about 20 or so) from the users of my android application who are all also on android 4)

**Comment by benmajor** [comment]
Okay, if it works on the simulator without problem, there's not much I can do to assist without more info I'm afraid.

**Comment by dyaga787** [comment]
> Okay, if it works on the simulator without problem, there's not much I can do to assist without more info I'm afraid.

android 4.4.2
its not works fine
swipe event does not always work, just few times of ten
proof https://youtu.be/61oJZl1uVV0

**Comment by benmajor** [comment]
This is related to the threshold on the swipe, and the fact that the `swipeend` event ends outside of the demo area. If you're having problems with this, you can change the threshold of the swipe event using the `data-` attributes.
