### ISSUE TITLE
singletap not firing on samsung s5 android 5.0

### ISSUE THREAD

**Issue by BillTheGoat** [benmajor/jQuery-Touch-Events#104]
just loaded my app on my friend's s5, and singletap was not working at all. no problems with swipe gestures (after the on tapmove chain I came up with in another issue). 

touchswipe demo page on built-in internet browser shows singletap very sporadic. it will fire, but rarely.

ps. i have limited time to access this device.

pps. the doubletap is pretty regular, so it seems like something having to do with the timer?

**Comment by benmajor** [comment]
Are you referring specifically to `singletap` or `tap`? If the former, it definitely looks like some kind of timing issue. Was this using the native Android browser?

**Comment by BillTheGoat** [comment]
singletap. I can get my hands on the phone again, but not for a week at least. native android browser (not Chrome) and webview. I saw a lot of log items I don't get on my htc or in the emulators, where samsung basically proxies the touch events and relays them to the app it seems. Sorry, exact messages are not on the tip of my tongue! I tried changing the basic tap times and pixel fuzziness to no effect. Perhaps you could point me to something else to look at and I can give them a shot next chance I get.

**Comment by BillTheGoat** [comment]
Singletap was missing the slop factor, others were not ... I found I could reproduce on other devices.

FIX (perhaps needs to be styled to your standards):

After line 401 (`tapTimer = window.setTimeout(function () {`)

**Add:**

**`var diff_x = (start_pos.x - end_pos_x),
           diff_y = (start_pos.y - end_pos_y);`**

Change line 402 `if (!$this.data('doubletapped') && !$this.data('tapheld') && (start_pos.x == end_pos_x) && (start_pos.y == end_pos_y)) {`

**To:**

**`if (!$this.data('doubletapped') && !$this.data('tapheld') && (((start_pos.x == end_pos_x) && (start_pos.y == end_pos_y)) || ((diff_x >= -(settings.tap_pixel_range) && diff_x <= settings.tap_pixel_range && diff_y >= -(settings.tap_pixel_range) && diff_y <= settings.tap_pixel_range)))) {`**

**Comment by benmajor** [comment]
This has now been implemented in the latest commit: https://github.com/benmajor/jQuery-Touch-Events/commit/72719010ac3650c255f2a227209821b1025e23a2
