### ISSUE TITLE
Multiple taphold listeners causing odd behavior

### ISSUE THREAD

**Issue by benmcmaster** [benmajor/jQuery-Touch-Events#106]
I am trying to get this working with jquery Sortable and TouchPunch. When sortable is activated it blocks scrolling and sorts the elements on `touchstart`. I wanted to activate sortable on `taphold` instead of `touchstart`. There is a cool hack to set the `touchstart` event to the `taphold` event  in TouchPunch so that sortable starts on a `taphold`.

This worked great until I added another `taphold` listener so that the sortable handler could get some additional styles. When there are two listeners on the same elements, only one of them will clear the timeout in the `touchend` of the `taphold`. So the other one will trigger the `taphold` event after 750ms.

http://jsfiddle.net/vbebyg1e/9/

In the example above when you tap and hold and element, it will turn yellow and you can sort just fine. However, if you just tap on an element, after 750ms it will turn yellow. The `taphold` event associated with Sortable gets canceled, but the `taphold` event associated with turning the element yellow is not canceled and gets triggered.

Any thoughts?

**Comment by benmcmaster** [comment]
I fixed it. 

It looks like the timers have too much scope. They are getting stomped on with subsequent listeners. I limited the scope of the timers to their respective setup functions.

See pull request:
https://github.com/benmajor/jQuery-Touch-Events/pull/107

Is there a reason why the timers are part of the settings object that I don't see?

**Comment by benmajor** [comment]
Thank you, there was no reason for the scope of the timers being as they were -- merely an oversight on my part. I've merged the request now, thanks for your contribution.
