### ISSUE TITLE
null is not an object errors

### ISSUE THREAD

**Issue by sphism** [benmajor/jQuery-Touch-Events#108]
Using version 1.0.5 in drupal 7 with jquery 1.7 and getting lots of Type error: null is not an object

![web_inspector_ _bada5s_ _safari_ _192_168_178_22_ _companies](https://cloud.githubusercontent.com/assets/2357045/17539371/d365b532-5f01-11e6-8fc9-899e3ed7e082.png)

**Comment by sphism** [comment]
Well I fixed it locally.

in the image above $this is $(window) and $this.offset doesn't exist.

So i just replaced:
- '...pageX - $this.offset().left)' >>>> '....pageX - ($this.offset() ? $this.offset().left : 0))'
- '...pageY - $this.offset().top)' >>>> 'pageY - ($this.offset() ? $this.offset().top : 0))'

So top and left offsets default to 0 if they aren't set.

Seems to have fixed the issue for me

**Comment by benmajor** [comment]
This has now been fixed in the latest commit: https://github.com/benmajor/jQuery-Touch-Events/commit/72719010ac3650c255f2a227209821b1025e23a2
