### ISSUE TITLE
Line 401 undefined variable / scope: tapTimer

### ISSUE THREAD

**Issue by fmp777** [benmajor/jQuery-Touch-Events#109]
Based on a very quick lookover, it seems line 401
`tapTimer = window.setTimeout(function () {`

Might need some scoping.  Looks like another function attempts to clear the timer, so might need to be window.tapTimer   if the variable is meant to be global?

**Comment by trostli** [comment]
I think I fixed this here - [6ccdb94](https://github.com/benmajor/jQuery-Touch-Events/pull/110/commits/6ccdb94ecebded7622af02ed3f00b0519bbaf4a0)

**Comment by benmajor** [comment]
Yes, @trostli's fix should indeed resolve the issue.
