### ISSUE TITLE
Singletap not fired on sensitive Android devices

### ISSUE THREAD

**Issue by danielhalldin** [benmajor/jQuery-Touch-Events#112]
A suggested solution is to add the swipe threshold, like this:
Line 406:
`if (!$this.data('doubletapped') && !$this.data('tapheld') && (Math.abs(start_pos.x - end_pos_x) < settings.swipe_v_threshold) && (Math.abs(start_pos.y - end_pos_y) < settings.swipe_h_threshold)) {
`

**Comment by benmajor** [comment]
Thank you for the heads-up. I'll add this to implement for v1.1.

**Comment by danielhalldin** [comment]
👍

**Comment by benmajor** [comment]
This has now been fixed in the latest commit: https://github.com/benmajor/jQuery-Touch-Events/commit/72719010ac3650c255f2a227209821b1025e23a2
