### ISSUE TITLE
Swipe does not get triggered on Android Browser 5.0

### ISSUE THREAD

**Issue by darthnorman** [benmajor/jQuery-Touch-Events#114]
Swipe does not get triggered on Android Browser 5.0.
Single Tap and Double Tap do work, but I don't get swipe to work.

**Comment by darthnorman** [comment]
More details to it: https://code.google.com/p/android/issues/detail?id=19827

**Comment by benmajor** [comment]
This unfortunately looks like a bug in the Android browser. I'll look for a fix, but this is a low priority.

**Comment by benmajor** [comment]
It appears that for now, there is no workaround despite having spent several weeks looking for a solution. I'm going to have to close this for now, sorry :(
