### ISSUE TITLE
`tapmove` in an element is fired event if not tap start in this element

### ISSUE THREAD

**Issue by ryuran** [benmajor/jQuery-Touch-Events#116]
`tapmove` in an element is fired even if not `tapstart` in this element

https://jsfiddle.net/5fkqzz8k/

tested on OsX with chrome

`tapmove` == `mousemove`

**Comment by benmajor** [comment]
This is the desired behaviour. `tapmove` == `mousemove`, in the same way that `tapstart` == `mousedown` (or `touchstart`). 

`tapmove` is being correctly triggered in the same way that `mousemove` is on the element:

https://jsfiddle.net/5fkqzz8k/1/

**Comment by ryuran** [comment]
I think i need `panmove` i will switch to hammer.js.
Thanks
