### ISSUE TITLE
Tap event not responding on iPad

### ISSUE THREAD

**Issue by googabeast** [benmajor/jQuery-Touch-Events#119]
On iPad, latest iOS, "tap" event does not fire. I have the event bound inside of a custom written plugin. All the events work fine for desktop, but as soon as I boot into the iOS simulator and real iPad devices I get no response.

$el.live("tap", function(e){
     alert(e.type);

     //do stuff
});

**Comment by benmajor** [comment]
Are you able to provide a jsFiddle which demonstrates this not working? Local tests show this to be working on iOS 10.2 (not tried in the latest beta, though).

**Comment by benmajor** [comment]
Any update on this at all?

**Comment by jtara** [comment]
I've noticed no tapstart, tapend in iOS uiWebView. (I am using it for sketch drawing). I only get tapmove. Assume this would also kill tap.

**Comment by benmajor** [comment]
Which version of the lib and iOS are you using? I have used the lib in the wild with uiWebView and `tap` events are definitely triggering.
