### ISSUE TITLE
Create release 1.0.6

### ISSUE THREAD

**Issue by amclin** [benmajor/jQuery-Touch-Events#120]
Since release version 1.0.6 hasn't been created, it doesn't show up on Cloudflare CDN:
https://cdnjs.com/libraries/jquery-touch-events

**Comment by benmajor** [comment]
Release 1.0.6 is now available, you may need to wait for the web interface to update, but direct URLs work find:

https://cdnjs.cloudflare.com/ajax/libs/jquery-touch-events/1.0.6/jquery.mobile-events.js
