### ISSUE TITLE
Option to set taphold_threshold?

### ISSUE THREAD

**Issue by jmwohl** [benmajor/jQuery-Touch-Events#121]
750ms is too long for our use, but it seems there's no way to modify this value. Am I missing something?

**Comment by benmajor** [comment]
Thanks Jonathan. I'll add this as a TODO for the next release (i.e. adding a `data-taphold-threshold` attribute to elements).

**Comment by benmajor** [comment]
This has now been introduced in the new version (1.0.7), please see https://github.com/benmajor/jQuery-Touch-Events/commit/76f6f4c7376092feeae22a073b8a36b1c477d523
