### ISSUE TITLE
Has no option "$.event.special.tap.emitTapOnTaphold" as jQuery Mobile

### ISSUE THREAD

**Issue by yikuo123** [benmajor/jQuery-Touch-Events#122]
```taphold``` may triggers an unexpected ```tap``` event, however jQuery-Touch-Events can not disable it

**Comment by benmajor** [comment]
Yes, that's right. Please refer to the [Docs](https://github.com/benmajor/jQuery-Touch-Events#4-the-events) about handling multiple events on the same item. Specifically for the `singletap` event:

> `singletap`:
> Unlike tap this event is only triggered once we are certain the user has only tapped the target element a single time. This will not be triggered by doubletap or taphold, unlike tap. Since we need to run some tests to make sure the user isn't double tapping or holding a tap on the target element, this event is fired with a short delay (currently of 500 milliseconds).
