### ISSUE TITLE
Latest release does not stick the one on npm

### ISSUE THREAD

**Issue by tifabien** [benmajor/jQuery-Touch-Events#126]
It seems there is a problem on release at npm side as when I go to the https://www.npmjs.com/package/benmajor-jquery-touch-events I see the latestversion is 1.0.5 but it seems not the case on this repo.

Can you enlight me? 
Thanks!!

**Comment by benmajor** [comment]
Hmm, this is odd since the versions are all correctly tagged as releases. I'll look into this. Thanks for bringing it to my attention.

**Comment by niftylettuce** [comment]
any update? @benmajor

**Comment by benmajor** [comment]
A little overdue admittedly, but this has now been done. Please see the new package which is the official one!

https://www.npmjs.com/package/@benmajor/jquery-touch-events
