### ISSUE TITLE
jQuery.attrFn is deprecated

### ISSUE THREAD

**Issue by hwi-jreimer** [benmajor/jQuery-Touch-Events#127]
It still works, but JQMigrate throws a warning.

`JQMIGRATE: Migrate is installed with logging active, version 1.4.1`
`JQMIGRATE: jQuery.attrFn is deprecated
migrateWarn @ jquery-migrate.js?1491586584:45`
`get @ jquery-migrate.js?1491586584:62`
`(anonymous) @ jquery.mobile-events.js?1491586584:30`
`(anonymous) @ jquery.mobile-events.js?1491586584:739`

**Comment by benmajor** [comment]
This is actually a false-positive. The lib originally used the undocumented `attrFn` feature but it was deprecated already in 2013. Please see the shim added to the library as work-around:

https://github.com/benmajor/jQuery-Touch-Events/blob/master/src/1.0.8/jquery.mobile-events.js#L31
