### ISSUE TITLE
1.0.8 throws an error when using jQuery 3.x.x

### ISSUE THREAD

**Issue by WeaponX86** [benmajor/jQuery-Touch-Events#128]
`	$(document).on('taphold','#test-taphold',function(){
		alert('taphold');
	});`

jquery-3.2.0.min.js:4 Uncaught TypeError: f.getClientRects is not a function
    at r.fn.init.offset (jquery-3.2.0.min.js:4)
    at jquery.mobile-events.min.js:27

**Comment by benmajor** [comment]
Can you confirm if the missing single quote in the `alert()` statement is a typo here, or is that how it appears in your code?

**Comment by WeaponX86** [comment]
That was just a typo in my post. I also tested with 3.0.0 as well and the same error is thrown.

**Comment by benmajor** [comment]
Okay thanks. I have been able to replicate this with the following:
https://jsfiddle.net/pjsamq2z/1/

I'll add it to the fix list!

**Comment by benmajor** [comment]
The fix for this is not to bind to `document`, but rather to `body`:

https://jsfiddle.net/pjsamq2z/2/
