### ISSUE TITLE
bind is deprecated

### ISSUE THREAD

**Issue by ctwist** [benmajor/jQuery-Touch-Events#129]
Your documentation shows how to use "bind". This is deprecated in jQuery 3, so I suggest that you should recommend that "on" should be used instead.
[http://api.jquery.com/bind/]

**Comment by benmajor** [comment]
The documentation also demonstrates the use of `on()` and `live()` so for now it'll stay. I'll remove it in v2.

**Comment by jtara** [comment]
.live(), though, is not only deprecated but removed. There should at least be a comment in the documentation.

**Comment by benmajor** [comment]
Thanks, the README has now been updated to remove mentions of `live()` and `bind()`.
