### ISSUE TITLE
Incorrect work doubletap

### ISSUE THREAD

**Issue by yamilramilev** [benmajor/jQuery-Touch-Events#131]
Hi!
When bind event as  `$(document).on('doubletap', 'SELECTOR'` event `doubletap` working incorrectly.
If first click to Block 1 and second click to Block 2, event fired, but should not.

https://jsfiddle.net/2avzofco/

**Comment by benmajor** [comment]
Thanks for the bug, it appears that the code is not checking the original target for double-tap elements when they have the same class. I'll push a fix for this.

**Comment by benmajor** [comment]
This should now be resolved with 1.0.9:
https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.9

Please allow some time for the CDN to detect the new release.
