### ISSUE TITLE
Removing event handlers which have not run yet

### ISSUE THREAD

**Issue by imbrish** [benmajor/jQuery-Touch-Events#139]
# Issue

Let's say we add handlers for two events:
```js
$('body').on('tapstart', function () { console.log('tapstart'); });
$('body').on('taphold', function () { console.log('taphold'); });
```
Now following functions will be registered by jQuery (can be checked with `console.log($._data( document.body, 'events'));`:
```
mousedown: tapStartFunc, tapHoldFunc1
mousemove: tapHoldFunc3
mouseup: tapHoldFunc2
taphold: ...
tapstart: ...
```
But let's unregister `taphold` before it has been executed even once:
```js
$('body').off('taphold');
```
Now following handlers remain:
```
tapstart: ...
```
Which will make `tapstart` handlers unable to fire, despite they were never turned off!

# Cause

The reason is that to remove handlers `$(this).data.callee` etc are used internally, however these properties are filled only after function runs at least once:
```js
$this.on(settings.startevent, function tapStartFunc(e) {
    $this.data('callee', tapStartFunc);
    ...
```

# Solution

Save functions in data properties already when adding internal handlers, for example:
```js
$this.on(settings.startevent, $this.data.callee = function tapStartFunc(e) {
    ...
```

**Comment by benmajor** [comment]
Could you please make a PR for this?

Thanks,
Ben.
