### ISSUE TITLE
Tap events not triggered on hybrid computers

### ISSUE THREAD

**Issue by bastienatome** [benmajor/jQuery-Touch-Events#141]
On hybrid computers (Tabs with Windows10 and physical keyboard detachable) we can use the trackpad or a mouse or the touch screen.
This library doesn't allow to do the both things, as the device is a touchable device, only the touch event are listened. (Tested on a Asus Transformer 3 Pro)

**Comment by benmajor** [comment]
Those devices should support pointer events, so they are not included in the scope of this particular library.
