### ISSUE TITLE
Repeated Errors Appearing

### ISSUE THREAD

**Issue by coderangerdan** [benmajor/jQuery-Touch-Events#144]
I keep getting tens of exceptions appearing in my Application Insights which end up in this code.

Cannot read property 'index' of null:

> HTMLDivElement.F                                 jquery.mobile-events.min.js    28
> HTMLDivElement.dispatch                     jquery-1.12.0.js                        5227
> HTMLDivElement.elemData.handle        jquery-1.12.0.js                       4879
> 

Any ideas what could be causing this, unfortunately i get no other stack trace so i cant track down where this issue originates.

**Comment by benmajor** [comment]
Could you post a jsFiddle that demonstrates the same behaviour?

**Comment by coderangerdan** [comment]
Sorry I'm afraid I cannot; as i said, all i get is those three calls in the stack trace of my massive app. I have no idea where its being called, whose calling it, when, or anything. This exception trace is reported via Application Insights so that is all i have at the moment.

I have no uploaded an unminified version of the TouchEvents file so i may get more information as to where it is happening at least.

I will update this when i have a bit more; as i understand i am giving you nothing to go on ... i just posted in case it was reported by anyone else.

**Comment by benmajor** [comment]
Okay, thanks. I don't suppose you're delegating events to the `document` object at all are you? There's a known issue with delegating to `document` with the library (see here: https://github.com/benmajor/jQuery-Touch-Events/issues/136).

**Comment by coderangerdan** [comment]
Not that I am doing no.

**Comment by coderangerdan** [comment]
The error is occurring in doubleTapFunc2 on line:
`if( delta < settings.doubletap_int && ( $( e.target ).index() == firstTap.index ) && delta > 100 )`

Unfortunately i have no stack trace, but this is coming from one of our office users and I know they havent got a touchscreen so i don't understand how they would even be in this function.

However, I have wrapped the event binding with your `isTouchCapable` helper method, which should eliminate the issue.
