### ISSUE TITLE
How to listener the event "drag"

### ISSUE THREAD

**Issue by jorhel** [benmajor/jQuery-Touch-Events#145]
hi!, first, this the best script to listen events from jquery. Is great!, thanks.
My question is: there is some possibility to add the event "drag"?
For listen the avance from the finger on a element pixel to pixel.

**Comment by benmajor** [comment]
There is no native event for this, no. But you could easily roll your own using `tapstart`, `tapmove` and `tapend`.

**Comment by jorhel** [comment]
It's just what I was looking for.
Thank you very much!

**Comment by jorhel** [comment]
PD:
How to get "gesture"from the event for get detlaX and deltaY?

**Comment by benmajor** [comment]
You will need to calculate it yourself using the start and end positions of your touch events.
