### ISSUE TITLE
Small problems with 'taphold' event

### ISSUE THREAD

**Issue by ghost** [benmajor/jQuery-Touch-Events#146]
Hi, I tried your library, and this is very useful. But like can I do to use the 'taphold' or other event on dynamically created elements? 
I use the following code `$(document).on("taphold", ("#div"), function(){...});` but in browser's console I have one error, related to code line n. 250, in refer to 'taphold'.
Thanks a lot.

**Comment by gae91** [comment]
ok, i've read this your [reply](https://github.com/benmajor/jQuery-Touch-Events/issues/136#issuecomment-333783117) now I'm understand can I do. 
If you want, you can close thi issue. Still Thanks!
