### ISSUE TITLE
Swipe Up/Down event.target is always the body element and not the element under the finder

### ISSUE THREAD

**Issue by enav** [benmajor/jQuery-Touch-Events#149]
Hello

First of all thanks for this awesome plugin. Is there any reason why swipe is always returning the body element and not the element under the finger just like tapstart event 

thanks

**Comment by benmajor** [comment]
That seems very strange. Are you delegating the event at all? Could you provide an example?

Thanks!
Ben.

**Comment by enav** [comment]
Hi

Here is an small example

// NOTE: Target is the expected one
$('body').on('tapstart', function(event){
	console.log("--------------");
	console.log('event = tapstart');
	console.log(event.target);
});

// NOTE: Target is always body
$('body').on('swipeup', function(event){
	console.log("--------------");
	console.log('event = swipeup');
	console.log(event.target);
});

Here is a live example http://jsbin.com/wovaxow/edit?html,js,output

Check the console to see the output

Regards

**Comment by benmajor** [comment]
Actually, this isn't a bug, but rather an issue with how JS delegates events. If you need to access the element the user swiped, you should use the second callback parameter, which contains the touch information. This will then include `startEvnt` and `endEvnt`, which in turn contain `target`, so you should use those instead:

```
$('body').on('swipeup', function(event, swipe){
    console.log("--------------");
    console.log('event = swipeup');
    console.log(swipe.endEvnt.target);
});
```
