### ISSUE TITLE
not support jquery 3.3.1

### ISSUE THREAD

**Issue by yokiijay** [benmajor/jQuery-Touch-Events#150]

**Comment by benmajor** [comment]
It is working fine:
https://jsfiddle.net/benmajor/9xfufdyg/

Are you sure you're not including 3.3.1 slim?

**Comment by benmajor** [comment]
Sorry, wrong

**Comment by yokiijay** [comment]
Thanks for ur reply, when using jq min 3.3.1 it just not working but work fine with 2.2 or below

please help me check this cdn jq if its fine?
https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js

**Comment by benmajor** [comment]
I've put together a jsFiddle and it works as expected using 3.3.1:
https://jsfiddle.net/benmajor/noxw757d/

Do you have a link to your project? Any errors in the console?

**Comment by yokiijay** [comment]
yep there is a error console, I don't with my laptop now, I'll sen it later to you thankyou again it's a perfect plugin easier than hammer. js

**Comment by alexcanessa** [comment]
I have the same problem it's because `$.event.props` has been deprecated in version 3.x.x https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed

**Comment by Mapiac** [comment]
Hi @benmajor , we used jQuery migrate to get onto 3.4.1 form 2.x but have since removed jQuery migrate after having done so. Must we still use jQuery migrate for this lib? We had a horrific time debugging only to determine JQM touch events are not fully comparable with jQuery 3+ so some rogue touchEvents (either touchStart or click) don't fire all the time currently. This lib looks much better. Tnx!

**Comment by benmajor** [comment]
Hi @Mapiac assuming that you don't need access to `$.event.props` inside your app, there is no need to add jQuery Migrate - everything is working fine with 3.3.1:

https://jsfiddle.net/6kgmqndj/

**Comment by ppetree** [comment]
So what's the final on this?  On 3.4.1 this doesn't work.  I get no errors in the console but no events either.

BTW, @benmajor - this is a really nice plugin and for those of us moving our last remaining projects away from jquery.mobile this is perfect!
