### ISSUE TITLE
Event.data being lost when combining tap/tapstart/tapend

### ISSUE THREAD

**Issue by zbauman3** [benmajor/jQuery-Touch-Events#152]
Hello, 

I'm attempting to add hover states to buttons on mobile using tapstart/tapend to add and remove a class. However, when I also add tap to the button and use its event.data in an animation callback (step) the event data is lost after tapend is triggered. This only happens when tap is set before tapstart/tapend. See this fiddle [http://jsfiddle.net/xpvt214o/625809/](http://jsfiddle.net/xpvt214o/625809/). This does not happen when using click/mousedown/mouseup, so I'm not sure if this is just a necessary limitation of the plugin or if it can be fixed. 

My solution so far is just to set event.data to a variable in the tap callback and use that variable in the step callback, but that seems unnecessary.

Thanks!

**Comment by benmajor** [comment]
Sorry, I'm not sure that I understand. Which event's tap data do you want to use in the `slideToggle`? The one from the `tap`, or from elsewhere?

**Comment by benmajor** [comment]
No problem!
