### ISSUE TITLE
How to enable the touch events on Surface Pro?

### ISSUE THREAD

**Issue by iramtay** [benmajor/jQuery-Touch-Events#154]
Hi,

If i tried the demo on the Surface Pro, it is able to detect Touch events from the mouse and touch screen.

Using the latest version, the mouse is not working.
How to allow both Mouse and Touch screen to be working together?

Thanks in advance.

**Comment by benmajor** [comment]
If the demo is working, but your development code isn't, there must be an issue with your development code.

Can you replicate the issue in a Fiddle so I can look into it?

**Comment by iramtay** [comment]
I am using V2 for development, but the demo is not. If i used the copy from demo on my local, it is behaving properly for touch screen and mouse.
I checked both versions and they are different.

Regards.
Sent from Yahoo 
 
  On Wed, 30 Jan 2019 at 17:50, Ben Major<notifications@github.com> wrote:   
If the demo is working, but your development code isn't, there must be an issue with your development code.

Can you replicate the issue in a Fiddle so I can look into it?

**Comment by iramtay** [comment]
Hi Ben,
Please find a summary of the results for the different versions as below.

1. events.js
        Touch screen: singletap, doubletap        Mouse: singletap, doubletap, swipeleft, swiperight, taphold

2. version 1.0.9
        Touch screen: singletap, doubletap, swipeleft, swiperight, taphold        Mouse: no event

3. version 2.0.0
        Touch screen: singletap, doubletap, swipeleft, swiperight        Mouse: no event

Regards.
Chee Chong 


    On Wednesday, January 30, 2019, 7:27:59 PM GMT+8, Ben Major <notifications@github.com> wrote:  
 
 
Do you have any errors in your console on the Surface Pro? Is it workable for you to regress to 1.0.9?

**Comment by benmajor** [comment]
Thanks, this is really strange. I assume that the reference to `events.js` at the start if your list is from the online demo?

Do you have any errors in the console?

**Comment by iramtay** [comment]
Yes, events is from online demo.
No error in console for all of them.

Sent from Yahoo 
 
  On Wed, 30 Jan 2019 at 21:54, Ben Major<notifications@github.com> wrote:   
Thanks, this is really strange. I assume that the reference to events.js at the start if your list is from the online demo?

Do you have any errors in the console?

**Comment by benmajor** [comment]
Are you able to let me know what the specific User Agent string of the browser you're using on the Surface Pro is, please? I suspect this might be related to a feature detection issue.

**Comment by iramtay** [comment]
Hi Ben,
Sorry, just saw your email.
How do you want me to extract the user agent?
Regards.
Chee Chong 

    On Thursday, February 7, 2019, 12:49:54 AM GMT+8, Ben Major <notifications@github.com> wrote:  
 
 
Are you able to let me know what the specific User Agent string of the browser you're using on the Surface Pro is, please? I suspect this might be related to a feature detection issue.

**Comment by benmajor** [comment]
Hey Chee,

You should be able to find it by visiting this URL on the device:
https://www.whatismybrowser.com/detect/what-is-my-user-agent

Thanks,
Ben.

**Comment by iramtay** [comment]
Hi Ben,
Here it is. It is the Surface Pro 2 running Google Chrome.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36


Regards.
Chee Chong 

    On Wednesday, February 20, 2019, 5:25:15 PM GMT+8, Ben Major <notifications@github.com> wrote:  
 
 
Hey Chee,

You should be able to find it by visiting this URL on the device:
https://www.whatismybrowser.com/detect/what-is-my-user-agent

Thanks,
Ben.

**Comment by benmajor** [comment]
Okay, so you're running Chrome? What happens if you use the native Edge browser?

**Comment by iramtay** [comment]
Using Edge, it does not give the chance to use the mouse. It just say Touch here using the demo site.
But we wanted to use the mouse and touch at the same time.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134


Regards.
Chee Chong 

    On Wednesday, February 20, 2019, 10:47:32 PM GMT+8, Ben Major <notifications@github.com> wrote:  
 
 
Okay, so you're running Chrome? What happens if you use the native Edge browser?

**Comment by benmajor** [comment]
Okay, so with 1.0.9 everything works as expected (per the demo), but when using 2.0.0 it doesn't support the touch events? Which version of jQuery are you using? Is it workable for you to regress to 1.0.9?
