### ISSUE TITLE
Delay between tap and alert()/confirm()

### ISSUE THREAD

**Issue by zbauman3** [benmajor/jQuery-Touch-Events#155]
I'm on iOS (12.1.4) using Safari. When you bind *tap* to an element and in the callback use alert() or confirm() there is roughly a 1 second delay between tapping and showing the alert.

This is only on mobile, desktop is fine. Also, it is only the alert that is delayed, anything else is immediate. 

Here is a fiddle https://jsfiddle.net/8n2tjLk4/1/

**Comment by benmajor** [comment]
Hmm, that's odd. I wonder if there's actually a bug (read feature) in iOS 12.1. I wonder if they delegate `alert()` and `confirm()` to ensure there's no long tap happening. I'll have to see if I can locate a device which has 12.1 installed and I'll let you know.

**Comment by zbauman3** [comment]
@benmajor Any update on this?

**Comment by benmajor** [comment]
This seems to be fixed in 13.1.2.
