### ISSUE TITLE
Wrong swipe direction

### ISSUE THREAD

**Issue by ctwist** [benmajor/jQuery-Touch-Events#165]
I am getting some incorrect swipe directions. If I swipe right, this is sometimes interpreted as a swipe up. This happens if I deviate slightly from a flat sideways swipe.

I looked at the code. The problem is in these statements:

                if (originalCoord.y > finalCoord.y && (originalCoord.y - finalCoord.y > v_threshold)) {
                    swipedir = 'swipeup';
                }
                if (originalCoord.x < finalCoord.x && (finalCoord.x - originalCoord.x > h_threshold)) {
                    swipedir = 'swiperight';
                }

If a slight vertical swipe amount exceeds the threshhold, it is interpreted as swipeup, even though a much greater horizontal swipe occurred.

If there is more horizontal movement than vertical movement, this should be interpreted as swiperight.

Edit:
Actually it is the next 2 statements that "win":

                if (originalCoord.y < finalCoord.y && (finalCoord.y - originalCoord.y > v_threshold)) {
                    swipedir = 'swipedown';
                }

So the swiperight is interpreted as swipedown.

**Comment by benmajor** [comment]
Thanks for the heads up. Are you able to share a basic working example which demonstrates this? I will be happy to look into it, but I fear that it could be difficult. The library doesn't know anything about other events that are bound to the element, only the one that it is currently occurring.

Is it not viable that you can increase the threshold for a vertical swipe?

**Comment by ctwist** [comment]
I have attached a fixed version of jquery.mobile-events.js. I have tested it and it has fixed the problem.
(I have not attached a file before; I hope I have done it correctly)

[jquery.mobile-events.txt](https://github.com/benmajor/jQuery-Touch-Events/files/4524095/jquery.mobile-events.txt)

**Comment by benmajor** [comment]
Thanks for the fix. I have now released a new version which includes this fix:
https://github.com/benmajor/jQuery-Touch-Events/commit/5db124d1c0ec506d48ff76789e471538d5f26497
