### ISSUE TITLE
Not compatible with jQuery 3.6

### ISSUE THREAD

**Issue by AlbinFarstun** [benmajor/jQuery-Touch-Events#171]
If I go with jquery migrate (only tested with 3.0.0) it works fine, otherwise this is the output of the console:

jquery-3.6.0.min.js:2 Uncaught TypeError: r.getClientRects is not a function
    at S.fn.init.offset (jquery-3.6.0.min.js:2)
    at tapMoveFunc (jquery.mobile-events.js:132)
    at dispatch (jquery-3.6.0.min.js:2)
    at v.handle (jquery-3.6.0.min.js:2)

**Comment by benmajor** [comment]
I've just put this jsFiddle together, and it seems to run fine with 3.6?

https://jsfiddle.net/7xa0z23L/1/

**Comment by AlbinFarstun** [comment]
@benmajor you are correct sir! The error only occurs when I try to bind to window apparently. $(window).on('tapstart', ...) fails, tried it out in the fiddle. Not that big of a deal :)

**Comment by benmajor** [comment]
Ah yes, there is a known issue for binding to window actually. If you search the closed issues, you'll find it. Basically, just bind to document 😉
