### ISSUE TITLE
Tap hold and double tap not working properly

### ISSUE THREAD

**Issue by brahmikumar** [benmajor/jQuery-Touch-Events#61]
I am developing album application in that, i added singletap, doubletap and taphold event to one element.
 working fine,but some times when i click doubletap, taphold event fires after that other events not working even onClick function also not working until i close and reopen app.

**Comment by tukaram57** [comment]
I am also experiencing the same kind of issue in developing app..
I am using single tap but app is working as desired when i hold the tap and not by single tap.

**Comment by benmajor** [comment]
`singletap` should only be used if you need to have `doubletap` support too. For most cases, you should just be able to use `tap`. Please confirm if this is something that you can do.

**Comment by tukaram57** [comment]
thanks for your input.
here is my code.. its for sample flashlight..
document.addEventListener("backbutton", function() {
    // pass exitApp as callbacks to the switchOff method
    window.plugins.flashlight.switchOff(exitApp, exitApp);
}, false);
document.addEventListener("deviceready", callThis, false);
$().ready(function() {
    $(".ui-content").height($.mobile.getScreenHeight());
    $("#offImg").hide();
    $("#onImg").on("tap", offfun);
    $("#offImg").on("tap", onfun);
});

function callThis() {



    window.plugins.flashlight.available(function(isAvailable) {
        if (isAvailable) {

            // switch on


        } else {
            alert("Flashlight not available on this device");
        }
        window.plugins.flashlight.switchOn(); // success/error callbacks
may be passed

        // switch off after 3 seconds
        setTimeout(function() {
            window.plugins.flashlight.switchOff(); // success/error
callbacks may be passed
        }, 600000);
    });
}

function exitApp() {
    navigator.app.exitApp();
}


function onfun() {
    window.plugins.flashlight.switchOn();
    $("#onImg").show();
    $("#offImg").hide();


    // switch on


}

function offfun() {
    window.plugins.flashlight.switchOff();
    $("#offImg").show();
    $("#onImg").hide();

}



here I need hold the button for a while to make the light off.. if I just
tap the button for a moment then it will trigger the event(on/off) and
again come back to original event(off/on) vice verca.

**Comment by hachigoro** [comment]
Not sure if it is related, but are you using the minified file or the full one? The minified does not have all the latest updates yet. I submitted some fixes to the taphold not long ago, and they might help, but those are only on the full file (not the .min).

**Comment by benmajor** [comment]
It is likely an issue that the minified file was not in sync with the latest updates. Please try again and see how you fair.
