### ISSUE TITLE
Not working in Android 4.4.4 

### ISSUE THREAD

**Issue by varunnayyar** [benmajor/jQuery-Touch-Events#63]
Hi, I am working on phonegap app and i am using this library for swipeup,swipedown,swiperight & swipeleft events.I tested it on android 4.2 and on web it works fine but on android 4.4.4 it does't work(on iphone i have not tested).Does this library supports android and iphone native apps or am i doing something wrong.
i appreciate any guidance.

Thanks
varun nayyar

**Comment by benmajor** [comment]
Thanks for your message. Does it work in Android 4.4.4 without a Cordova wrapper?

**Comment by varunnayyar** [comment]
i opened (http://ben-major.co.uk/jquery-mobile-events/) demo page in chrome of android 4.4.4 and its working .

**Comment by benmajor** [comment]
OK, it looks like an issue with the Cordova wrapper. Are you sure that the paths to jQuery and the plugin are resolving correctly?

**Comment by varunnayyar** [comment]
Yes, after building app i tested it on android 4.2 and 4.4 it is working on 4.2.

**Comment by benmajor** [comment]
OK, then it's likely an issue with the event handling of Cordova / WebView. Unfortunately, I do not have a 4.4.4 device to test, and the emulator seems to work fine. Without further debug information, I can't see this being fixed any time soon.

**Comment by varunnayyar** [comment]
Ok Sir.Thanks for your time.
