### ISSUE TITLE
order of swipe detection

### ISSUE THREAD

**Issue by commonpike** [benmajor/jQuery-Touch-Events#64]
in my local installation, i changed the order of swipe detection, making vertical swipes comes last in the code (and hence prevail over horizontal swipes).

on mobile devices, vertical swipes are a common way to scroll, people who do that clumsy are likely to trigger a horizontal swipe by accident. by changing the order, you can prevent accidental horizontal swipes by limiting threshold_y - anything above the threshold would be a vertical swipe.

**Comment by benmajor** [comment]
I don't quite understand your point. Are you suggesting that the order of the detection be changed by default in the library, or simply stating this as a useful comment for others? Thanks for the clarification.
