### ISSUE TITLE
Taphold triggers on tap, after delay

### ISSUE THREAD

**Issue by bekkii77** [benmajor/jQuery-Touch-Events#65]
'taphold' action handlers are triggering even without holding down on the element for the specified amount of time.  They are being called after a short tap, after a delay equaling 750ms.  I have reproduced this on Firefox and Mobile Chrome.  I increased the taphold threshold to 2000ms to verify that it was being called regardless of holding down on the element.  After a tap on the element, and then waiting two seconds, my action handler filed.

**Comment by benmajor** [comment]
Thanks. Could you please share your code that replicates this issue so that I can look into it?

**Comment by bekkii77** [comment]
Sorry, not as simple as it sounds.  I'm still working on it.  It's starting to look like an interaction with another library, still tracking it down.

**Comment by benmajor** [comment]
Any more updates on this at all?
