### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by Poil2Q** [benmajor/jQuery-Touch-Events#69]
Hey ben

Can you make a bower.json to download you lib with it ?

Thank !

**Comment by benmajor** [comment]
Hi @Poli2Q,

It's on the list for 1.0.1 :)

Regards,
Ben.

**Comment by benmajor** [comment]
A Bower package has now been added in 1.0.1:
https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.1

**Comment by Poil2Q** [comment]
Hey,

Not added to bower repository ?

http://bower.io/search/?q=jquery-touch-events

Regards

**Comment by benmajor** [comment]
It's registered now, the problem was with `bower.json` being inside the 1.0.1 release folder.

Thanks!
