### ISSUE TITLE
tapend not fire in Samsung default Internet browser when touch and swipe

### ISSUE THREAD

**Issue by leekung** [benmajor/jQuery-Touch-Events#71]
Test on Samsung Internet Browser shipped with Samsung Galaxy A8 Android 5.1.1
Browser user agent is 
Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-A800F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36

tested on your test page http://ben-major.co.uk/jquery-mobile-events/ 
Step: 
1. Touch and console print - "tapstart" called
2. swipe to any direction and release finger

there is no swipe or tapend fire.

Tested on Google Chrome browser on the same device. everything work as expected. no issue found.

Thanks

**Comment by benmajor** [comment]
Thanks for your comment. Please bear in mind that the code running on the test page is **not** the current release code. 

Can you please try to put together a sample (using jsFiddle) using the latest push?

**Comment by leekung** [comment]
Hi
Actually I download latest code from master and use in my project.
Same result with test page on Samsung browser.

Here is jsfiddle test page http://jsfiddle.net/8upohvkL/
result
http://postimg.org/image/yoix3oied/

as you can see on Console log. 
tapstart fire 3 times but no tapend on each.
this is because I tap and swipe 3 times

Thanks

**Comment by benmajor** [comment]
Hi,

I cannot replicate the behaviour using the UA string you specified. For example:
http://postimg.org/image/nyi1mmhsb/

What is the exact process flow you followed?

**Comment by leekung** [comment]
Hi,

this is actual mobile device not emulator. I hope you can find some Android device that shipped with its default browser. eg. Samsung, Asus, Vivo 
I mean the Internet icon in screen shot 
http://postimg.org/image/b1iig482n/

**Comment by leekung** [comment]
It seems this is Chrome on Android bug. many reports here
http://stackoverflow.com/questions/2987706/touchend-event-doesnt-work-on-android
there maybe workaround for this but I have no idea how to apply
http://blog.mobiscroll.com/working-with-touch-events/

Hope you can fix it.
Thanks

**Comment by benmajor** [comment]
Thanks for the further research and links. 

It appears that the only way this bug can be resolved in certain versions and installs of Android is to use `preventDefault()` on the `touchmove` event. However, since that would prevent native scrolling, I will not implement it into the library yet, because that goes against the plugin's aims. However, what you will need to do is add an `preventDefault()` call in the `swipe` event. 

This event definition begins on line 517, and specifically you should find line 561, and replace with:

```
function touchMove(e) {
    e.preventDefault();
```
