### ISSUE TITLE
[Feature Request]  tapmoveout support

### ISSUE THREAD

**Issue by kirantpatil** [benmajor/jQuery-Touch-Events#74]
Hi,

I am trying Touch events to replace event listeners.

I have mouseover and mouseout events and replaced with tapmove and tapend.

The tapmove works but if I take mouse out of object it is not invoking tapend.

I think we need tapmoveout event as well to resolve this issue.

Any suggestions welcome.

Thanks.

**Comment by kirantpatil** [comment]
Code snippet:

 $(rect).off().one('taphold', callback);
 $(rect).on('tapmove', callback1);
 $(rect).on('tapend', callback2);

 function callback1() {
                    this.style.setProperty("opacity", "1");
                  }

                  function callback2() {
                    this.style.setProperty("opacity", "0.5");
                  }

When I move mouse on SVG rect element its opacity changes but when I move out of rect it remain same. Taphold and Tapmove works on svg rect element but not tapend.

Please guide me how to resolve this issue.

Thanks.

**Comment by benmajor** [comment]
`tapend` should behave as expected, it does with other elements. Can you put together a jsFiddle or similar so that I can investigate?

Thanks,
Ben.

**Comment by kirantpatil** [comment]
I can't since it is part of the application, please find the below link

https://github.com/kirantpatil/park-mgmt/blob/master/app/assets/javascripts/park_sse.js

**Comment by benmajor** [comment]
Hmm I'm going to have close this because I can't replicate it. All tests I have done using SVG and `tapmove` and `tapend` function correctly.
