### ISSUE TITLE
Doesn't respect touch identifier

### ISSUE THREAD

**Issue by EloB** [benmajor/jQuery-Touch-Events#76]
If you start touching with one finger and then touches with another finger. It will then trigger swipeend event when you released the second finger. Please use `touches` instead of `changedTouches` or look into `touchEvent.identifier`.

https://developer.mozilla.org/en-US/docs/Web/API/Touch/identifier

**Comment by benmajor** [comment]
Actually, the use of `changedTouches` is a legacy workaround for older versions of mobile browsers (some of which didn't play well with `touches` alone). This is on the list of things to be modified for 1.1.

Thanks,
Ben.

**Comment by EloB** [comment]
https://github.com/benmajor/jQuery-Touch-Events/pull/77

**Comment by benmajor** [comment]
Thanks, I have just merged this with the latest branch.

**Comment by EloB** [comment]
I was to quick with my previous PR. Didn't test it enough. Here is a fix for desktop. https://github.com/benmajor/jQuery-Touch-Events/pull/78

**Comment by benmajor** [comment]
Perfect, thank you!
