### ISSUE TITLE
Using rules in chrome gives the wrong position

### ISSUE THREAD

**Issue by scottieslg** [benmajor/jQuery-Touch-Events#79]
When using the rulers in Chrome, if I capture a singletap event, the touchData.position is wrong.  It includes the width and height of the chrome ruler.

On my specific environment, I'm testing simulating iPad.  The left of the screen should be 0, however, origEvent.touches[0].target.offsetLeft is set to 21.

Really, pageX/pageY should be used to get the offset of the visible view area.  This does not include the rulers and gives the click location from the page left/top, not the view area left/top.

**Comment by benmajor** [comment]
This is actually referenced by another issue now, and so I'll close this as a duplicate. Please see the other issue for updates:

https://github.com/benmajor/jQuery-Touch-Events/issues/82
