### ISSUE TITLE
Incorrect callback data offset

### ISSUE THREAD

**Issue by danielocdh** [benmajor/jQuery-Touch-Events#81]
The offset returned by the event data is being relative to the event origin element instead of the bound element.

I only tested with tapstart, tapend, tapmove, tap
Rough example (clicking the blue bar when the event is bound to the red circle)
https://jsfiddle.net/uda55h3z/

**Comment by benmajor** [comment]
Thank you, I will fix this in a push tonight.

**Comment by benmajor** [comment]
This should now have been fixed in the 1.0.3 release:
https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.3
