### ISSUE TITLE
Incorrect callback data position

### ISSUE THREAD

**Issue by danielocdh** [benmajor/jQuery-Touch-Events#82]
The position returned by the event data is incorrect. I tested tap event. All browsers return different values, but if you tap one point and then another, the difference between those 2 points seems to be correct, I tested with 1.0.2 for firefox and chrome, 1.0.0 for IE.

Example code without iframe
http://pastebin.com/UkBFafUp

The number seems to change when inside an iframe, for example iframe inside jsfiddle will return different values than simple html from pastebin:
https://jsfiddle.net/uda55h3z/1/

**Comment by benmajor** [comment]
Thanks, this was also reported by another user. Will be fixed in a push this evening (hopefully).

**Comment by benmajor** [comment]
This should now have been fixed in the 1.0.3 release:
https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.3
