### ISSUE TITLE
IE11Support

### ISSUE THREAD

**Issue by bostonmacosx** [benmajor/jQuery-Touch-Events#85]
I have this working in Opera,Firefox and Safari...however....not in IE11 Are they any tricks?

I'm in jquery 2.1.3 and had to back off of your latest releast back to 1.0.1 to get it to play nicely even in chrome or firefox.

**Comment by benmajor** [comment]
1.0.1 doesn't support IE11's Pointer Events (please see https://github.com/benmajor/jQuery-Touch-Events/issues/73).

You should be using 1.0.3 for the best compatibility. What problems were you facing in Chrome and Firefox? The demo page (http://lincweb.co.uk/labs/jquery-touch-events/demo/) works perfectly in Chrome, Safari and FF on OSX. 

Oh, and it's probably worth noting that Opera isn't officially supported, yet.
