### ISSUE TITLE
Jquery 2.1.3 and Touch 1.0.3 error

### ISSUE THREAD

**Issue by bostonmacosx** [benmajor/jQuery-Touch-Events#86]
When I use these libraries together:

```Uncaught TypeError: Cannot use 'in' operator to search for 'position' in undefined```

It is finding an error on jquery.min.js on line 3.

here is the code that the touch calls:

```
$(document).on('tap','.addtocart',function(event){
  var tempobj = {};
  if(!cart){
    //alert('inhere');
    cart = [];
  }
 parent = $(this).closest('.row');
 tempobj["shorty"]= $(parent).find("input[name='short']").val();
 tempobj["gender"]= $(parent).find("select[name='gender']").val();
 tempobj["size"]= $(parent).find("select[name='sizes']").val();
 tempobj["personalization"]= $(parent).find("input[name='personalization']").val();

 tempobj["quantity"]= $(parent).find("input[name='quantity']").val();
 tempobj["price"]= $(parent).find("input[name='price']").val();
 tempobj["id"]=cart.length.toString();

 for (var key in tempobj) {
   if (tempobj.hasOwnProperty(key)) {
     if(tempobj[key]=='' && key!='personalization'){
       alert(key+'Unable to add to cart. Please make sure all fields are filled correctly.');
       return;
     }
   }
 }

 cart.push(tempobj);

  refreshCart();
  alert('Item Added');
});
``

**Comment by benmajor** [comment]
Do you have a URL that I can check, or are you able to put together a jsFiddle or similar so I can investigate further?

**Comment by bostonmacosx** [comment]
I'm on a time crunch so I just set up a quick single page for this person...here is the one using the 1.0.3 release. Give me about 5 minutes to get it operational...

http://aacboosters.org/orders03.php

**Comment by benmajor** [comment]
OK, it looks like there's an issue with the event delegation, since the error is triggered when clicking anywhere on the page. Will take a look for you now.

**Comment by bostonmacosx** [comment]
Thanks in advance.

**Comment by benmajor** [comment]
It appears that the issue was indeed with the event delegation to `document`. Changing the `on()` statements to be bound to `body` works fine:

http://lincweb.co.uk/labs/jquery-touch-events/debug/

Change the definitions as follows:

    $('body').on('tap','#cartheader',function(event) {
        $('#cart').toggleClass("cartheight cartheightauto");
    });

**Comment by bostonmacosx** [comment]
I changed all of the (document) to ('body') that fixed the error but I still have no love in IE11.

**Comment by benmajor** [comment]
Are you using 1.0.3? Any errors in the console at all? If looks like a
Pointer Event issue.

**Comment by bostonmacosx** [comment]
No errors in IE if I open up the DEV console and go from "EDGE" to 10 for the rendering engine it starts working again.

**Comment by bostonmacosx** [comment]
and yes I'm using 1.0.3 in the page you are looking at

**Comment by benmajor** [comment]
Please try with 1.0.4 now, this should fix the issue:
https://github.com/benmajor/jQuery-Touch-Events/blob/master/src/1.0.4/jquery.mobile-events.js
