### ISSUE TITLE
Why position() is used instead of offset()?

### ISSUE THREAD

**Issue by cervengoc** [benmajor/jQuery-Touch-Events#87]
I've just began to experiment with this project, and seems to be very promising. I just needed a lightweight gesture implementation for jQuery (HammerJS is quite robust for me currently).

As I've read through the code I noticed that when calculating the `offset` property of the event data at several places, you use jQuery `position`. If I understand correctly the purpose of the `offset` property is to give the coordinates relative to the target element's topleft corner. If so, shouldn't it be rahter jQuery `offset` of the element?

**Comment by benmajor** [comment]
No, using jQuery's `offset` property on events is not sufficiently robust enough for us to work with this library. Event delegation and bubbling sometimes mean that the values returned by `offset` are not correct, or are relative to a higher parent than we need, particularly when using fixed or absolute positioning. 

Also, `offset` returns to the current target of the event, **not the bound target** which is the expected return value of the `offset` property in the touch event parameters.

You can see how it was improved in the following push:

https://github.com/benmajor/jQuery-Touch-Events/commit/6fe893d76e2d198da11ec6fb41e85cea3fcfc44f?diff=split

This is not a valid bug, so am going to close.

**Comment by cervengoc** [comment]
Thank you for the fast response, and sorry if I have some noob points. Actually I was planning to contribute in the future with implementing scale and rotate events, that's why I was looking at the sources.

I see that commit, but that's a different story I think (about event target or bound element). I see that you have to use the bound target, I would expect that too.

But still, if I have an element with an offset parent other than the document node, I will get incorrect value when you subtract if from pageX/Y. Or am I completely wrong? I'll do some tests later.

**Comment by benmajor** [comment]
Thanks! Glad to learn that you're planning on contributing. Gestures have been in the pipeline for sometime now (including scale, rotate, shake and others) but I want to get the core features working and stable before we look to a 2.0.0 release.

This has actually been discussed in a couple of issues here on GitHub, you can check them out here:

https://github.com/benmajor/jQuery-Touch-Events/issues/82

Hopefully this will demonstrate why using `offset()` is not a viable option for the library.

**Comment by cervengoc** [comment]
Ok, but I'm not talking about target or bound element, I'm talking about position relative to document (offset()) or position relative to offset parent (position())

Check this out, it gives incorrect results IMO:
https://jsfiddle.net/uda55h3z/5/

**Comment by benmajor** [comment]
Thanks! You're right, the position given in your example is reporting the wrong position, I will fix it in the next push over the weekend.

Yes, there was an earlier version which used `offset()`, but it didn't work so well. Will find a work around for the example you've given though. Thanks for your help!

**Comment by cervengoc** [comment]
If you could recap what exactly the problems were with offset I could maybe help. I personally would prefer using it if it's already present in jQuery for exaclty this purpose. Maybe there is some workaround or minor tweek.

**Comment by benmajor** [comment]
I managed to find some time to investigate, and it seems that regressing to `offset()` does the job:

https://jsfiddle.net/uda55h3z/6/

I have pushed a new version to 1.0.5, please see:

https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.5

**Comment by cervengoc** [comment]
Thank you

I've further examined the source code and found lots of questions and possible refactoring/refinements. I currently don't have time to start working on it, but in the future may I contact you for a chat in some way?

**Comment by benmajor** [comment]
Yes, of course. Comments, feedback and improvements are always very welcome :+1:
