### ISSUE TITLE
Can 'tap' event fallback to 'click' event in Microsoft Edge browser?

### ISSUE THREAD

**Issue by elantion** [benmajor/jQuery-Touch-Events#89]
In desktop, MS Edge dose not use 'MSPointer' by default. It has to be enable manually. If it disable, we can not trigger a 'tap' event when using mouse left click.
So, I suggest 'tap' event can fallback to 'click' event in MS Edge. Is that OK?
Thank you

**Comment by benmajor** [comment]
Please see 1.0.5, it uses `ontouchstart` rather than MSPointer events:

https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.5

**Comment by elantion** [comment]
I already use 1.05 version, but it did not work for me. I check the event, it seem like the desktop Edge still using 'mousedown' event. I change the 'tap' event to 'click', it work perfectly. By the way I use Iscroll(https://github.com/cubiq/iscroll). Maybe iscroll has conflict with jquery-Touch-Event?
Thanks your reply!

**Comment by benmajor** [comment]
1.0.5 removed MSPointer events, and does in fact use touchstart or mousedown. 

Yes, iScroll will cause some issues (mainly due to event propagation and default behaviour prevention). Unfortunately for now, there's no workaround available.

**Comment by elantion** [comment]
I use a dirty trick to make it work:
```
    var workEvent;
    $parent.on('tap click', '.child', function (event) {
        if(!workEvent){
            workEvent = event.type;
        }
        if(workEvent === event.type){
           //do what you want.
        }
    });
···
Not so elegant.

**Comment by elantion** [comment]
Sorry to border you again. I keep digging this issue and I found 'singletap' can be triggered. What's the different between 'tap' and 'singletap'? Could you can give me some tips? Maybe I can find a solution.
Thanks!
