### ISSUE TITLE
Correct naming of mouse vents on Github README

### ISSUE THREAD

**Issue by dragGH102** [benmajor/jQuery-Touch-Events#90]
May I suggest to use the correct name for javascript event in section 4. The event? (since it's basically what's written in the plug-in JS file)

       [mobile --> desktop]
       tapstart --> mousedown (instead of 'clicking' which is misleading)
       tapend --> mouseup
.       ...and so on...

I believe it would be clearer and quicker to understand for an inexperienced developer

**Comment by benmajor** [comment]
I'm not sure that I follow your suggestion? This library triggers its own events, which have their own names. 

The event that the library triggers called `tap` isn't the same as a native `click` event, and similarly `tapstart` != `mousedown`...

**Comment by dragGH102** [comment]
I mean that where you specify the corresponding event on desktop , specifying its actual name would be better rather than just a "non for dev" explanation (e.g. Click in tapstart line)

-----Original Message-----

**Comment by benmajor** [comment]
Can you provide an example? Do you just mean an update to the README, or something more?

**Comment by dragGH102** [comment]
on github repository's 'code' tab (new layout) 

    4. The Events:
        tapstart  Fired as soon as the user begins touching an element (or clicking, for desktop environments).

but 'clicking' (click) != 'mousedown'

this can be misleading in my opinion

**Comment by benmajor** [comment]
Hm, I don't think it's so misleading. Taking out the parentheses, `mousedown` does represent the action when a *user **begins** clicking*

Thanks for the heads-up on the typo, though!
