### ISSUE TITLE
Offset error when target is document

### ISSUE THREAD

**Issue by dryaner** [benmajor/jQuery-Touch-Events#94]
in the events singletap and doubletap I obtain a javascript error when the target is document. (that is not normal, but sometimes happens).
the problem is provoked because is not possible calculate the offset of document and the plugin is not preventing this situation.

**Comment by benmajor** [comment]
Yes, this is a known bug when binding events to `document`. As a 'dirty' hack until I can get to rewrite everything for v2, bind to `body` instead.
