### ISSUE TITLE
improv tauch slider

### ISSUE THREAD

**Issue by teleskop** [benmajor/jQuery-Touch-Events#96]
hi
thanks for jQuery-Touch-Events .
but i want events as this slider:
http://s1.picofile.com/d/4c3cb03b-f2c5-408a-9e4e-8048e9b81b21/simple_fade_slideshow_slider.zip

its in:
http://www.jssor.com/demos/simple-fade-slideshow.slider

please Notify me
Thankyou

**Comment by benmajor** [comment]
Hello,

I am sorry, but this is beyond the scope of the library. You can implement your own 'live' scrolling using the numerous events that are bundled with this framework, but at this time I do not have any intentions of releasing 'live' swiping events.

Thanks,
Ben.

**Comment by teleskop** [comment]
Thanks
