### ISSUE TITLE
Marshmallow Issues

### ISSUE THREAD

**Issue by richardegil** [benmajor/jQuery-Touch-Events#97]
Have you experienced any issues using this library in Android Marshmallow (v 6.0.1)? We can't seem to get the events to fire.

**Comment by benmajor** [comment]
I have not tested the events in Marshmallow at all. Are there any errors or debug information you can provide?

**Comment by richardegil** [comment]
I will try to get some debug info. White now nothing seems to happen when an event is triggered, but works in older versions of Android and iOS

**Comment by richardegil** [comment]
I was able to run the demo link on an Android phone running Marshmallow and everything worked. Thanks for responding so quickly.
