### ISSUE TITLE
doubletap firing when tap 2 different items quickly

### ISSUE THREAD

**Issue by docmattman** [benmajor/jQuery-Touch-Events#98]
I have a list of items with the doubletap listener added.  If I tap one, then quickly tap a different one, the doubletap fires.  Seems like it should only fire if the same element is tapped twice, not any two elements in the selector. 

Here is an example of the code I'm using:

            $('ul.items-list').on('doubletap', 'a.item-link', function(e)
            {
                alert('doubletapped!');
            });

As stated, I tap one item in the list, then immediately tap a different list item and the event fires.

**Comment by benmajor** [comment]
Thanks for posting this, and sorry for the delay; I'll get this fixed in a new Push.

**Comment by docmattman** [comment]
No problem.  Thanks for the update.

**Comment by trostli** [comment]
Just submitted a PR to fix this
