### ISSUE TITLE
Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by maxwellhibbert** [benmajor/jQuery-Touch-Events#99]
I recently updated to version 1.5 from a pre-1.0 release and I'm getting this error when using 'tap':   "Uncaught TypeError: Cannot read property 'left' of undefined".

**Comment by benmajor** [comment]
Thanks. Are you able to put together a demo on jsFiddle or similar which replicates the problem?

**Comment by maxwellhibbert** [comment]
Here you go: http://codepen.io/cunningstunts/pen/PNPzzX
While setting that up, I noticed the problem only occurs when attaching the event to the document, works fine on the element itself but I rarely do that. You can see the tap fail on the event attached the doc.
I'm not using the offset values at all in my project, so I just commented out the offending lines and all works well again.
Thanks for a really useful plugin by the way :)

**Comment by benmajor** [comment]
Thanks for that. There is already another bug in the system about binding to `document`. Please see this:

https://github.com/benmajor/jQuery-Touch-Events/issues/94

I'll close this issue for now, because it's already on the list for v2.

**Comment by maxwellhibbert** [comment]
Ah, sorry about that, I checked for any open issues so didn't see anything related.
Thanks again,

**Comment by benmajor** [comment]
No problem!
